version: '3.1'

services:
  server:
    container_name: mas_server
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT}:80
    volumes:
      - ./:/var/www/html/
    environment:
      HOSTNAME_DB: ${HOSTNAME_DB}
      USERNAME_DB: ${USERNAME_DB}
      PASSWORD_DB: ${PASSWORD_DB}
      DB: ${DB}
      SECRET: ${SECRET}
      BASE_URL: ${BASE_URL}
      DOMAIN: ${DOMAIN}
    networks:
      - mas
  db:
    container_name: mas_db
    image: mysql
    restart: always
    hostname: mas
    ports:
      - 3303:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mas
      MYSQL_ROOT_HOST: '%'
      TZ: Asia/Ho_Chi_Minh
    volumes:
      - ./.docker/mysql:/var/lib/mysql
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    networks:
      - mas
  adminer:
    container_name: mas_adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - mas

networks:
  mas:
    driver: bridge
